### ISSUE TITLE
Android Version?

### ISSUE THREAD

**Issue by geirman** [evetstech/react-native-settings-list#11]
This looks great, but it appears to be iOS centric. Are you planning to create an Android themed version?

**Comment by evetstech** [comment]
Could you be more specific?  The example I created was iOS, but I don't see any reason why you can't use it for Android as well.  I could try to create an example for a default android settings page as well, if that's what you're asking.

**Comment by geirman** [comment]
Yes, exactly :)

**Comment by evetstech** [comment]
Sure, shouldn't be a problem.  I'll try to get something out soon-ish

**Comment by geirman** [comment]
You're the man! I'll send out a tweet to draw attention once you do :)

**Comment by evetstech** [comment]
A quick example can be found in the example folder.  No callbacks tied to it, but I don't think it's needed, there is already documentation on that.

**Comment by geirman** [comment]
Great work! As promised, I've sent out a tweet to help draw attention...
https://twitter.com/geirmanc/status/778999005535621120
