### ISSUE TITLE
Publish to npm for RN 0.36 support

### ISSUE THREAD

**Issue by gutenye** [evetstech/react-native-settings-list#13]
Hi, 

It seems RN 0.36 support has been added in master branch, would you publish to npm?

Thanks.

**Comment by evetstech** [comment]
Yes, I just published it, but I do feel like I need to explain why I didn't to begin with.  The fix actually didn't affect 0.36 support at all, at least from my tests.  I tested with RN0.28 and RN0.37 with the change, and without, and it didn't make a difference.  That is why I accepted the PR, as it's dead code.  Though I didn't see a reason to merge it into NPM as it wouldn't have affect anyone's projects, and at the worst case cause people to have to update it without reason.  I do understand keeping npm up-to-date with the codebase though, so it I suppose updating it won't hurt.
