### ISSUE TITLE
Item is not highlighted on touch

### ISSUE THREAD

**Issue by mayask** [evetstech/react-native-settings-list#2]
Hey!

Thanks for the awesome package.

When I click on `SettingsList.Item` it doesn't change it's background like a normal touch control.

Looking at the code I managed to fix it by removing a `underlayColor='transparent'` props from the underlying `<TouchableHighlight>` component.

``` jsx
<TouchableHighlight key={'item_' + index} underlayColor='transparent' onPress={item.onPress}>
  <View style={[styles.itemBox, {backgroundColor: item.backgroundColor ? item.backgroundColor : this.props.backgroundColor}]}>
```

I was wondering, since that underlay is transparent, I can work it around using different background colors, but, unfortunately, I either had to break my design or highlight simply didn't work. 

Could you explain what is the main reason you put it in in the first place, and if we could at least make `underlayColor` configurable via `SettingsList.Item` props?

Thanks for your answer.

**Comment by mayask** [comment]
Would you accept a PR for that?

**Comment by evetstech** [comment]
The transparent underlayColor was mainly used for a subtle response to a button press, but I completely get where you are coming from.  I used it in that regard,  but I can see someone else using it in a different manner.  I opened up underlayColor as a prop, and set it's default to transparent.

**Comment by mayask** [comment]
@evetstech thanks!
