### ISSUE TITLE
SettingsList.Item should have a itemStyle prop

### ISSUE THREAD

**Issue by dividezero** [evetstech/react-native-settings-list#23]
Item has a leftMargin of 15 in styles.titleBox that offsets the border as well. Id like to change the itemView style but there doesnt seem to be an API for it. I can do a pull request if needed to allow itemStyle as a prop of SettingsList.Item. Thoughts?

**Comment by evetstech** [comment]
I opened up all of the hardcoded styles that I'm using, allowing for you to customize all of it, but also allows for it to have the same default settings as well
