### ISSUE TITLE
Can't start scroll from section titles

### ISSUE THREAD

**Issue by robclouth** [evetstech/react-native-settings-list#3]
Hey, thanks for this, it's saved me loads of time!
One thing that doesn't feel quite right though is that you can't drag on the section titles to scroll. Any ideas for how to get around this?

Thanks

**Comment by evetstech** [comment]
Can you post some sample code?  The code I used in my sample seems to scroll on the section titles.

**Comment by evetstech** [comment]
I'll be closing this for now.  Feel free to reissue something if you run into it again, along with some sample code!
