### ISSUE TITLE
React.createClass deprecated

### ISSUE THREAD

**Issue by jbrodriguez** [evetstech/react-native-settings-list#38]
It's a warning since RN 0.47 (I seem to remember)

These lines

https://github.com/evetstech/react-native-settings-list/blob/master/index.js#L273
https://github.com/evetstech/react-native-settings-list/blob/master/index.js#L296

need to be changed.

The easiest solution would be to ```npm i create-react-class``` and https://facebook.github.io/react/docs/react-without-es6.html

Awesome library by the way !

**Comment by MartinCamen** [comment]
+1
