### ISSUE TITLE
How to turn the switch on/off indivudually

### ISSUE THREAD

**Issue by shirleycharlin** [evetstech/react-native-settings-list#5]
Hi!

This is actually not an issue. I would like to ask how to actually turn the switch on/off individually with your example.

**Comment by evetstech** [comment]
Sure not a problem.  In the example I made, the switch works as followed:  I have a member variable switchValue that I declared in the constructor, along with a bind function that is tied to a function that will change the state as it is toggled:
`constructor(){
    super();
    this.onValueChange = this.onValueChange.bind(this);
    this.state = {switchValue: false, loggedIn: false};
  }`

Next, the declaration of the switch in SettingsList.Item, all I need to do is pass a hasSwitch={true} to tell the class that this item will be a switch-type item, along with all the properties attached to it.
`<SettingsList.Item
              icon={
                  <Image style={styles.imageStyle} source={require('./images/airplane.png')}/>
              }
              hasSwitch={true}
              switchState={this.state.switchValue}
              switchOnValueChange={this.onValueChange}
              hasNavArrow={false}
              title='Airplane Mode'
              titleStyle={{fontSize:16}}
            />`
The property 'switchState' is tied to my current state of switchValue, and the property 'switchOnValueChange' is your callback, in which i tied to the function we created a bind for earlier.  The example is very simplistic, and only changed the state (which is what's tied to the UI's switch state ON/OFF), but you can extend upon that function to do whatever it is that your switch wants to do in that callback function.

I hope that helps!
