### ISSUE TITLE
Switch color

### ISSUE THREAD

**Issue by mayask** [evetstech/react-native-settings-list#6]
Is there a way to change item's switch color?

If no, would you accept a PR for that?

Thanks

**Comment by evetstech** [comment]
I accept all PR requests that enhance the module.  Feel free to do a PR;  If you want to work on it, it is as much your project as it is mine!

**Comment by 6axter82** [comment]
`<SettingsList.Item
							title='Vote'
							hasNavArrow={false}
							hasSwitch={true}
							onTintColor={'blue'}
							switchState={this.state.newVoteSwitchValue}
							switchOnValueChange={(value) => this.setState({newVoteSwitchValue: value})}
						/>`

onTintColor, I wanted to ask if I am implementing it correct. cause I don't see any change for the switch color. Could you please help?
