### ISSUE TITLE
'On' state did not last for long

### ISSUE THREAD

**Issue by shirleycharlin** [evetstech/react-native-settings-list#8]
I have updated the onValueChange(value) to the ones below. However, neither the 'On' state or active color stay for long. I am also not able to find any timer in your source code. Can I know where did I go wrong?

 onValueChange(value){
    var switchValue = switchValue
    if (switchValue == true){
      this.setState({
        switchValue: value
      })
    }else{
      switchValue: null
    }
  }

**Comment by evetstech** [comment]
You have to have a variable in your constructor as switchValue.  That constructor variable also has to be tied to the switch state as well to update the interface.  I don't know why you would need a timer of any sort.
